// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package dbqueries

import (
	"context"
)

const getAllDestinations = `-- name: GetAllDestinations :many

SELECT id, city, country, price, days FROM destinations
`

// queries/destinations.sql
func (q *Queries) GetAllDestinations(ctx context.Context) ([]Destination, error) {
	rows, err := q.db.Query(ctx, getAllDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.Country,
			&i.Price,
			&i.Days,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
