// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Destination struct {
	ID            int32
	City          string
	Country       string
	Price         pgtype.Numeric
	Days          int32
	Origin        pgtype.Text
	DepartureDate pgtype.Date
	ReturnDate    pgtype.Date
	DepartureAt   pgtype.Timestamptz
	ReturnAt      pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
